### ISSUE TITLE
Meta-System doc Landing Page model

### ISSUE THREAD

**Issue by zelcion** [mapikit/meta-system-docs#4]
## Description
Development of a visual model for the landing page.

## Requirements
- [x] Page should be built starting with WHY we're building MSYS, and what is the pain we're solving.
- [x] Next sections should highlight how such pain is addressed
- [x] Final sections show what exactly is Meta-System.

--------
### Why?
**Never repeat your lines, or reinvent architecture. Just code.**
Meta-System offers a unique approach to development, minimizing the need for boilerplate code and intricate architectural setups, with no hidden parts (It's open source).

- NPM CTA
- Get Started CTA
- Star on GitHub CTA
- Has a diagram showcasing Meta-Editor and the capability of using your own code as an Addon

### How?
**Instant Architecture, Zero Hassle.**
Meta-System handles the heavy lifting of structuring and connecting your software components, allowing you to effortlessly reuse code, even across projects, and with your favorite libraries.

**Concentrate on what matters most—what you build.**
- Diagram showing software components connected to each other.
- At the side, there's a selector which changes the shown image to another one, highlighting a specific part of the diagram, and giving it a short explanation
![image](https://github.com/mapikit/meta-system-docs/assets/13098424/983f3957-6259-4de3-8465-036d6d0452d1)
- CTA "Join the community of builders"

**Bring your own code**
With a tiny core, and built to be as extensible as you need it, Meta-System can import `.js` files to do anything your solution requires.

- CTA: Create your own Addon
- Diagram importing code from NPM, a cloud CDN, from Local Storage.

**Open Format**
Your whole system is configured using JSON. Manually write it if you want, or download the Meta-Editor to visually create your software. Launching Meta-System is as simple as running a command pointing to your `.json`.

- Screenshot of Meta-Editor
- CTA for downloading it

### What?
**A System to be Any System**
Meta-System is an extensible and modular no-code engine, built for everyone, free and open-source.
It frees you, the developer, to work on what makes your software truly unique.

- CTA Discord.
- CTA Support us.
- Section showing supporters logos and slots
